apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jitsi
bases:
#- https://github.com/jitsi-contrib/jitsi-kubernetes/tree/main/doc/kustomize
#- kustomization_base.yaml
- 010-jvb-service.yaml
- 020-rbac.yaml
- 030-deployment.yaml
- 040-web-service.yaml


resources:
- 041-ingress.yaml

patchesStrategicMerge:
- 010-deployment.yaml
